#!/bin/bash

echo -e "\033[33mcleaning up imgsurf builds...\033[0m"

if [[ -d ./build/ ]]
then
    rm ./build/ -rf
fi

if [[ -d ./bin/ ]]
then
    rm ./bin/ -rf
fi

if [[ -d ./build/ ]]
then
    rm ./build/ -rf
fi

echo -e "\033[32mcleaned imgsurf!\n\033[0m"
