#!/bin/bash

if [[ -f "./vendor/datasurf/clean" ]]
then
    pushd "./vendor/datasurf/" > /dev/null
    ./clean
    popd > /dev/null
fi

echo -e "\033[33mcleaning up imgsurf builds...\033[0m"

if [[ -d ./bin/ ]]
then
    rm ./bin/ -rf
fi

pushd ./assets/ > /dev/null
for written in *reconstructed*
do
    if [[ ! -f $written ]]
    then
        continue;
    fi

    rm $written
done
popd > /dev/null

echo -e "\033[32mcleaned imgsurf!\n\033[0m"
