#!/bin/bash

if [[ ! -d "./obj/" ]]
then
    mkdir ./obj/
fi

if [[ ! -d "./build/" ]]
then
    mkdir ./build/
fi

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

premake5 ecc
premake5 gmake

pushd ./build/
make

if [[ $? != 0 ]]
then
    exit -1
fi

if [[ $1 = "--compile-only" ]]
then
    exit 0
fi

popd

chmod +x ./bin/release/imgsurftest
./bin/release/imgsurftest
