#!/bin/bash

if [[ ! -d "./obj/" ]]
then
    mkdir ./obj/
fi

if [[ ! -d "./build/" ]]
then
    mkdir ./build/
fi

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

echo ""
echo -e "\033[36mcompiling imgsurf...\033[0m"
echo ""

premake5 ecc
premake5 gmake

pushd ./build/

if [[ $1 = "debug" ]]
then
    make config=debug_linux
elif [[ $1 = "release" ]]
then
    make config=release_linux
elif [[ $1 = "asan" ]]
then
    make config=asan_linux
else
    echo -e "\033[31m\nERROR: invalid make config: $1.\033[0m"
    exit -2;
fi

if [[ $1 = "--compile-only" ]] || [[ $2 = "--compile-only" ]]
then
    exit 0
fi

if [[ $? != 0 ]]
then
    echo -e "\033[31mERROR: failed to compile.\033[0m"
    exit -1
fi

if [[ $2 = "--compile-only" ]]
then
    exit 0
fi

popd

chmod +x ./bin/release/imgsurftest
./bin/release/imgsurftest
