#!/bin/bash

if [[ ! -d "./obj/" ]]
then
    mkdir ./obj/
fi

if [[ ! -d "./build/" ]]
then
    mkdir ./build/
fi

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

premake5 ecc
premake5 gmake

pushd ./build/
make
popd
